name: YEA BOI!
description: Boom Ting!
author: Devbench
author_email: admin@devben.ch
permalink: pretty

exclude: ['node_modules/', '**/*.less']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
