name: Devbench
description: Freelance Web Developers in Kent
author: Devbench
author_email: admin@devben.ch
permalink: pretty

exclude: ['node_modules/', '**/*.less', 'assets/javascripts/vendor', 'assets/javascripts/lib']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
